sylius_ui:
    events:
        bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.content:
            blocks:
                before_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 35
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.before_header
                header:
                    template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/Show/_headerWidget.html.twig"
                    priority: 30
                after_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.after_header
                breadcrumb:
                    template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/Show/_breadcrumb.html.twig"
                    priority: 20
                after_breadcrumb_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.after_breadcrumb
                content:
                    template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/Show/_content.html.twig"
                    priority: 10
                after_content_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.after_content


        bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.contents:
            blocks:
                before_contents_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 100
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.contents.before_contents

                before_orders_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 95
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.contents.before_orders
                orders:
                    template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/Show/_ordersWidget.html.twig"
                    priority: 90
                after_orders_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 85
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.contents.after_orders

                before_payments_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 80
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.contents.before_payments
                payments:
                    template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/Show/_paymentsWidget.html.twig"
                    priority: 75
                after_payments_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 70
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.contents.after_payments

                before_subscription_contents_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 65
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.contents.before_subscription_contents
                subscription_contents:
                    template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/Show/_subscriptionContentsWidget.html.twig"
                    priority: 60
                after_subscription_contents_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 55
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.contents.after_subscription_contents

                before_subscription_schedule_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 50
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.contents.before_subscription_schedule_legacy
                subscription_schedule:
                    template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/Show/_subscriptionScheduleWidget.html.twig"
                    priority: 45
                after_subscription_schedule_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 40
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.contents.after_subscription_schedule_legacy

                after_contents_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 0
                    context:
                        event: bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.contents.after_contents

        bitbag_sylius_mollie_plugin_mollie.admin.mollie_subscription.show.sidebar:
            blocks:
                payments:
                    template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/Show/_sidebarPayments.html.twig"
                    priority: 30
                transitions:
                    template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/Show/_sidebarTransitions.html.twig"
                    priority: 30
