bitbag_sylius_mollie_plugin_cancel_subscription_mollie:
  path: /account/order/{orderId}/subscription-mollie/cancel
  methods: [PUT]
  defaults:
    _controller: bitbag_sylius_mollie_plugin.controller.action.admin.mollie_subscription_controller:applyStateMachineTransitionAction
    _sylius:
      repository:
        method: findOneByOrderIdAsString
        arguments:
          - $orderId
      state_machine:
        graph: mollie_subscription_payment_graph_manual
        transition: cancel
      redirect: referer
      flash: bitbag_sylius_mollie_plugin.subscription.cancelled
