sylius_resource:
    resources:
        bitbag_sylius_mollie_plugin.mollie_subscription_product:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusMolliePlugin\Entity\MollieSubscriptionProduct
                interface: BitBag\SyliusMolliePlugin\Entity\MollieSubscriptionProductInterface
