sylius_resource:
    resources:
        bitbag_sylius_mollie_plugin.mollie_subscription:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusMolliePlugin\Entity\MollieSubscription
                interface: BitBag\SyliusMolliePlugin\Entity\MollieSubscriptionInterface
                repository: BitBag\SyliusMolliePlugin\Repository\MollieSubscriptionRepository
