sylius_grid:
    grids:
        bitbag_sylius_mollie_plugin_mollie_subscription:
            driver:
                name: doctrine/orm
                options:
                    class: "%bitbag_sylius_mollie_plugin.model.mollie_subscription.class%"
            actions:
                item:
                    show:
                        type: show
                        options:
                            link:
                                route: bitbag_sylius_mollie_plugin_mollie_subscription_show
                                parameters:
                                    id: resource.id
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                state:
                    type: twig
                    label: bitbag_sylius_mollie_plugin.ui.subscription.fields.state
                    sortable: ~
                    options:
                        template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/Grid/Field/state.html.twig"
                orders:
                    type: twig
                    label: bitbag_sylius_mollie_plugin.ui.subscription.fields.orders
                    path: .
                    options:
                        template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/Grid/Field/orders.html.twig"

                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                    sortable: ~
                    options:
                        format: 'Y-m-d H:i:s'
                startedAt:
                    type: datetime
                    label: bitbag_sylius_mollie_plugin.ui.subscription.fields.started_at
                    sortable: ~
                    options:
                        format: 'Y-m-d H:i:s'
            filters:
                createdAt:
                    type: date
                    label: bitbag_sylius_mollie_plugin.ui.subscription.grid.filters.created_at
                    options:
                        field: createdAt
                        label: test
                startedAt:
                    type: date
                    label: bitbag_sylius_mollie_plugin.ui.subscription.grid.filters.started_at
                    options:
                        field: startedAt
                        label: test
                state:
                    type: subscription_state
                    label: bitbag_sylius_mollie_plugin.ui.subscription.grid.filters.state
                    options:
                        field: state
                        label: test
    templates:
        filter:
            subscription_state: "@BitBagSyliusMolliePlugin/Admin/Logger/Grid/_theme.html.twig"
