bitbag_sylius_mollie_plugin_mollie_subscription:
    resource: |
        alias: bitbag_sylius_mollie_plugin.mollie_subscription
        section: admin
        path: /mollie/subscription
        permission: true
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: bitbag_sylius_mollie_plugin_mollie_subscription
        vars:
            all:
                subheader: bitbag_sylius_mollie_plugin.ui.subscription_list
            index:
                icon: 'tags'
    type: sylius.resource
