bitbag_sylius_mollie_plugin_mollie_subscription:
    resource: |
        alias: bitbag_sylius_mollie_plugin.mollie_subscription
        section: admin
        path: /mollie/subscription
        permission: true
        templates: "@SyliusAdmin\\Crud"
        only: ['index']
        redirect: update
        grid: bitbag_sylius_mollie_plugin_mollie_subscription
        vars:
            all:
                subheader: bitbag_sylius_mollie_plugin.ui.subscription_list
            index:
                icon: 'tags'
    type: sylius.resource

bitbag_sylius_mollie_plugin_mollie_subscription_show:
    path: /mollie/subscription/{id}
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_mollie_plugin.controller.action.admin.mollie_subscription_controller:showAction
        _sylius:
            section: admin
            permission: true
            template: "@BitBagSyliusMolliePlugin/Admin/MollieSubscription/show.html.twig"


bitbag_sylius_mollie_plugin_mollie_subscription_cancel:
    path: /mollie/subscription/{id}/cancel
    methods: [PUT]
    defaults:
        _controller: bitbag_sylius_mollie_plugin.controller.action.admin.mollie_subscription_controller:applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: mollie_subscription_payment_graph_manual
                transition: cancel
            redirect: referer

bitbag_sylius_mollie_plugin_mollie_subscription_pause:
    path: /mollie/subscription/{id}/pause
    methods: [PUT]
    defaults:
        _controller: bitbag_sylius_mollie_plugin.controller.action.admin.mollie_subscription_controller:applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: mollie_subscription_payment_graph_manual
                transition: pause
            redirect: referer

bitbag_sylius_mollie_plugin_mollie_subscription_resume:
    path: /mollie/subscription/{id}/resume
    methods: [PUT]
    defaults:
        _controller: bitbag_sylius_mollie_plugin.controller.action.admin.mollie_subscription_controller:applyStateMachineTransitionAction
        _sylius:
            permission: true
            state_machine:
                graph: mollie_subscription_payment_graph_manual
                transition: resume
            redirect: referer
