name: Build and publish

on:
    push:
        branches:
            - master
    release:
        types: [ created ]
    schedule:
        -   cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
    build_and_publish:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -   uses: actions/checkout@v2

            -   name: Declare GIT variables
                id: vars
                shell: bash
                run: |
                    echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | awk '{print tolower($0)}')"
                    echo "##[set-output name=repository;]$(echo ${{ github.event.repository.name }} | awk '{print tolower($0)}')"
                    echo "##[set-output name=registry_repository;]$(echo ${{ github.event.repository.name }} |sed -e 's/\([A-Z]\)/-\L\1/g' -e 's/^-//')"
                    echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
            -   name: Repository name
                run: echo ${{ github.event.repository.name }}

            -   name: Extract tag name
                id: tag
                uses: actions/github-script@0.2.0
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    script: |
                        return context.payload.ref.replace(/\/refs\/tags\//, '');
            -   name: Git Tag
                run: echo ${{ steps.tag.outputs.result }}

            -   name: Docker Login
                uses: docker/login-action@v1.10.0
                with:
                    registry: registry.bitbag.shop
                    username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
                    password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
                    logout: true

            -   name: Build and push php
                uses: docker/build-push-action@v2
                with:
                    file: ./Dockerfile
                    context: .
                    target: result_php
                    push: true
                    tags: |
                        ${{ secrets.DOCKER_REPOSITORY_HOSTNAME }}/${{ steps.vars.outputs.registry_repository }}/${{ steps.vars.outputs.branch }}:latest
                        ${{ secrets.DOCKER_REPOSITORY_HOSTNAME }}/${{ steps.vars.outputs.registry_repository }}/${{ steps.vars.outputs.branch }}:${{ steps.vars.outputs.sha_short }}
